### ISSUE TITLE
why not use dp mst for Dual Monitors 

### ISSUE THREAD

**Issue by inascf** [yuqi/Deskmini-310-Hackintosh#2]
i also have a diskmini 310, when i use dp Monitor is fine, but use WhateverGreen for fake hdmi monitor  i should plug when system boot login.
i see you use dell u2715h monitor, it support dp mst why not use this,

eg
[Dell U2715H DisplayPort Not Working ](https://multimonitorcomputer.com/solved/dell-u2715h-displayport-daisy-chaining.php)

[How to Configure U2415 Monitor Daisy Chaining on Intel HD Graphics](https://www.dell.com/support/article/us/en/04/sln295251/how-to-configure-u2415-monitor-daisy-chaining-on-intel-hd-graphics?lang=en)

**Comment by yuqi** [comment]
Hi @inascf,
 
I gave a try on what Dell recommends, It doesn't work. macOS only recognized one (the primary), and dual monitors are mirrored.

But this daisy chain works on my ATX build ( Z77X + i5 2500k + RX 470 )... 

FYI: I also got some unconfirmed post says that 

> [DisplayPort 1.2 support and daisy chain](https://www.tonymacx86.com/threads/displayport-1-2-support-and-daisy-chain.222890/post-1511270)
> DisplayPort daisy chaining only (sort of..) works with AMD graphics

**Comment by inascf** [comment]
thks
