### ISSUE TITLE
What's differences between BrcmFirmwareRepo.kext and BrcmFirmwareData.kext

### ISSUE THREAD

**Issue by isudox** [yuqi/Deskmini-310-Hackintosh#3]
As this title mentioned, some guys' efi kexts use BrcmFirmwareData.kext and works well, why your efi choose BrcmFirmwareRepo.kext?

**Comment by isudox** [comment]
RehabMan's repo informs that:
"Also, install one firmware kext BrcmFirmwareData.kext or BrcmFirmwareRepo.kext, depending on installation location, never both.

BrcmFirmwareRepo.kext: Install to /System/Library/Extensions (/Library/Extensions on 10.11 and later). This kext is much more memory efficient than BrcmFirmwareData.kext and is the preferred configuration.

BrcmFirmwareData.kext: Most appropriate for EFI/Clover/kexts. BrcmFirmwareRepo.kext, while much more memory efficient, cannot be injected as can BrcmFirmwareData.kext"

I think you should put BrcmFirmwareData.kext in Clover/kexts folder, not BrcmFirmwareRepo.kext.

**Comment by yuqi** [comment]
@isudox Thanks

I think you are right, I should use `BrcmFirmwareData.kext` in EFI/Clover/kexts/folder.
