### ISSUE TITLE
installation is ok but after restart stuck on boot

### ISSUE THREAD

**Issue by barron9** [yuqi/Deskmini-310-Hackintosh#5]
hi, 

i am stuck here,niresh mojave, asrock hm310 itx ac with i3 8100.. whats not working here?

![IMG_20190730_232924](https://user-images.githubusercontent.com/27488285/62194525-b5479b00-b382-11e9-9ae2-9d2b97391c15.jpg)

**Comment by yuqi** [comment]
GPU issue? try remove the node `Devices -> Properties -> PciRoot(0x0)/Pci(0x2,0x0)`...
