### ISSUE TITLE
audio on mac os 10.15?

### ISSUE THREAD

**Issue by HemingwayZ** [yuqi/Deskmini-310-Hackintosh#7]

**Comment by yuqi** [comment]
I just upgraded to Catalina and everything is working except Bluetooth.

You may re-add Lilu and AppleALC to solve the audio problem.

[The audio broke but I re-added the Lilu KEXT and rebooted and that fixed it.](https://www.tonymacx86.com/threads/update-directly-to-macos-catalina.284463/page-2)
