### ISSUE TITLE
请问bios版本是多少？

### ISSUE THREAD

**Issue by GerrieWell** [yuqi/Deskmini-310-Hackintosh#9]
你好。请教下bios 版本是多少？
我的是4.2，试了网上好几个EFI，都在启动安装程序时卡住。
用的https://blog.xjn819.com/?p=7#comment-248 这个人的bios配置。10.14.6
用黑果小兵的镜像自带EFI能安装，但是核显有问题。不能放视频。

**Comment by yuqi** [comment]
BIOS 版本好像是1.10，最早的版本
升级过一次，启动不起来就降级回去了

**Comment by zi-l** [comment]
@GerrieWell 
我的bios也是4.2，用的黑果小兵`10.15.1`镜像，核显也有问题，安装后桌面一直很卡，根本无法操作。另外我也遇到了安装卡住的情况（两分钟），黑果小兵的解决方法在这里[Common-problems-and-solutions-in-macOS-Catalina-10.15-installation](https://blog.daliansky.net/Common-problems-and-solutions-in-macOS-Catalina-10.15-installation.html) ，然而对我没有效，我参考了下面的EFI: [guide-macos-catalina-on-asrock-deskmini-310-with-9th-gen-intel-core-cpu-dual-boot](https://www.tonymacx86.com/threads/guide-macos-catalina-on-asrock-deskmini-310-with-9th-gen-intel-core-cpu-dual-boot.287709/) ，发现UEFI文件夹缺少了文件`EmuVariableUefi.efi`，添加完该文件后正常安装了。你可以试试

@yuqi 
请问我的问题是核显问题吗？你是怎么解决的？我用的4k显示屏。

**Comment by yuqi** [comment]
@zi-l 9代U也是CoffeeLake，和8代配置应该是相同的

核显问题最初的解决，就是设置正确的 `ig-platform-id`，参照了
[[Guide] Intel Framebuffer patching using WhateverGreen](https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/)，尝试多个 Coffee Lake 的ID，最后使用的是 *3E9B0007*

另外再做过的一些尝试是解决双显示器的问题，过程记不太清了。最早应该是直接注入edid来解决的，后来参考了 [liminghuang/asrock_deskmini310_hackintosh](https://github.com/liminghuang/asrock_deskmini310_hackintosh) 使用了其它的配置也解决了双显示器的问题

参考：
1. [[Guide] Intel Framebuffer patching using WhateverGreen](https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/)
2. [Coffee Lake帧缓冲区补丁及UHD630 Coffee Lake ig-platform-id数](https://blog.daliansky.net/Coffee-Lake-frame-buffer-patch-and-UHD630-Coffee-Lake-ig-platform-id-data-finishing.html)

**Comment by yuqi** [comment]
@GerrieWell 
这里 https://github.com/liminghuang/asrock_deskmini310_hackintosh 有 BIOS 4.x 的 DSDT Patch，可以尝试下
